[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "3dapplications"
version = "0.0.1"
authors = [
  { name="Ranadheer", email="radr314@gmail.com" },
]
description = "applications"
readme = "README.md"
requires-python = ">=3.8

